USE [master]
GO

/****** Object:  Database [MyWorkplace]    Script Date: 28/01/2020 01:00:35 ******/
CREATE DATABASE [MyWorkplace]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyWorkplace', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\MyWorkplace.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyWorkplace_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\MyWorkplace_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [MyWorkplace] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyWorkplace].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyWorkplace] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyWorkplace] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyWorkplace] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyWorkplace] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyWorkplace] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyWorkplace] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MyWorkplace] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyWorkplace] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyWorkplace] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyWorkplace] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyWorkplace] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyWorkplace] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyWorkplace] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyWorkplace] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyWorkplace] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MyWorkplace] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyWorkplace] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyWorkplace] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyWorkplace] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyWorkplace] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyWorkplace] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [MyWorkplace] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyWorkplace] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MyWorkplace] SET  MULTI_USER 
GO

ALTER DATABASE [MyWorkplace] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyWorkplace] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyWorkplace] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyWorkplace] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MyWorkplace] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MyWorkplace] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MyWorkplace] SET  READ_WRITE 
GO

